version: "3"
services:

  oes-postgres:
    image: registry.docker-cn.com/library/postgres:10-alpine
    container_name: oes-postgres
    restart: always
    volumes:
      - $PWD/data/oes-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=OES_DB
      - POSTGRES_USER=oes_db_user
      - POSTGRES_PASSWORD=oes_db_pass


  oes-server:
    image: registry.cn-hangzhou.aliyuncs.com/maplefater/oes
    container_name: oes-server
    depends_on:
      - oes-postgres
    volumes:
      - $PWD/data/oes-server:/data
    environment:
      - POSTGRES_DB=OES_DB
      - POSTGRES_USER=oes_db_user
      - POSTGRES_PASSWORD=oes_db_pass
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"

  oj-redis:
    image: registry.docker-cn.com/library/redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - $PWD/data/oj-redis:/data

  oj-postgres:
    image: registry.docker-cn.com/library/postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - $PWD/data/oj-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  judge-server:
    image: registry.cn-hangzhou.aliyuncs.com/maplefater/judge_server
    container_name: judge-server
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
      - /judger_run:exec,mode=777
      - /spj:exec,mode=777
    volumes:
      - $PWD/data/oj-backend/test_case:/test_case:ro
      - $PWD/data/judge_server:/log
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=HelloWorld123

  oj-backend:
    image: registry.cn-hangzhou.aliyuncs.com/maplefater/oj_backend
    container_name: oj-backend
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
    volumes:
      - $PWD/data/oj-backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=HelloWorld123
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:81:8000"